[features]
seeds = false
skip-lint = false
[programs.devnet]
raffle_simple = "JBmbzzuur92hmKRoDegWpaL6tmLcHsaJTVzRwv68S9mZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
